[package]
name = "fancheng"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A framework for legal norm programming"
license = "MIT"

[dependencies]
chrono = "0.4"
uuid = "1.0"